on: 
  push:
    branches: [master,benchmarking]


name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: testing
        run:  |
          sudo apt-get install seqkit
          bash tests/10_benchmark.sh


